version: '3'
# local:container
services:
  api:
    build: .
    container_name: container_api
    restart: always
    tty: true
    stdin_open: true
    volumes:
      - .:/app/backend
    ports:
      - 3001:3001
    environment:
      - MONGO_URI=mongodb://database:27017/databaseName
      - PORT=3001
    depends_on:
      - database
    networks:
      - api_network

  database:
    container_name: container_db
    image: mongo:5.0.7
    restart: always
    ports:
      - 27017:27017
    networks:
      - api_network

networks:
  api_network:
    driver: bridge